apiVersion: v1
kind: Service
metadata:
  name: flowforge-server
  namespace: flowforge
  labels:
    app.kubernetes.io/name: flowforge-server
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: flowforge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flowforge-server
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
